name: insurance_project       # your dbt project name
version: '1.0.0'
config-version: 2

# Default target is set in dbt Cloud environment
profile: insurance_project

# Where your models live
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

flags:
  use_materialization_v2: true

# Auto-generate schema tests
require-dbt-version: ">=1.5.0"

# Materializations
models:
  insurance_project:  # match your project name
    # Bronze layer
    bronze:
      +schema: bronze
      +materialized: table
      +persist_docs:
          relation: true
          columns: true

    # Silver layer
    silver:
      +schema: silver
      +materialized: table
      +persist_docs:
          relation: true
          columns: true

    # Gold layer
    gold:
      +schema: gold
      +materialized: table
      +persist_docs:
          relation: true
          columns: true

# # Configuring models
# # Full documentation: https://docs.getdbt.com/docs/configuring-models
